# Generated by Django 3.2.23 on 2023-12-09 17:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='items',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
